### ISSUE TITLE
Configuration and running script for Relation Extraction 

### ISSUE THREAD

**Issue by yanzhangnlp** [DevSinghSachan/syntax-augmented-bert#1]
Dear Devendra,

Thanks for your great work!  May I ask if you can share the parameter configuration details and running script for Relation Extraction task? I am grateful for that!

Best,
Yan

**Comment by DevSinghSachan** [comment]
Hi Yan,

Thank you for the interest in our work!
I have now added the config files and a demo run script for the TACRED revised dataset (relation extraction task).

**Comment by DevSinghSachan** [comment]
Also, I am closing this issue now. Feel free to reopen it in case there are any issues.
