### ISSUE TITLE
Is it possible to use this for sentence classification tasks?

### ISSUE THREAD

**Issue by nirmal2k** [DevSinghSachan/syntax-augmented-bert#5]
I'd like to use any of glue datasets and perform sentence classification.
If it's possible, could you please explain how to prepare input for this model?

**Comment by DevSinghSachan** [comment]
the TACRED relation extraction task closely resembles the sentence classification task.
You can look at the code for that.

You may also have to edit some parts of the code, but it should be easy to do.

**Comment by nirmal2k** [comment]
I was able to use it for sentence classification task 👍
